import Head from "next/head";

export default function HtmlHead({ routeTitle }) {
  const title = routeTitle
    ? `${routeTitle} | Create Next App`
    : "Create Next App";
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
